// Cross-repo golden test (docs/DESIGN_SF_COST_HISTORY.md §8, docs/IMPL_PLAN_SH4.md §4).
//
// starforce.js is a vendored copy of maplenEnhancebot's
// packages/engine/src/starforce.ts (type annotations stripped only - see the file header).
// It is NOT the source of truth. This test proves the copy still produces the same
// numbers as maplenEnhancebot's own parity fixtures (tools/parity/sf_fixtures/*), which
// were generated by the TypeScript original. If this test goes red, the vendored copy has
// drifted from the original and must be re-synced (do not edit starforce.js directly to
// silence a failure here).
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { expectedStarforceCostExact, requiredPriceStars } from "./starforce.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const fixture = JSON.parse(
  readFileSync(join(__dirname, "__fixtures__", "sf_expected.json"), "utf8"),
);

const RELATIVE_ERROR_LIMIT = 1e-12;

describe("expectedStarforceCostExact vs maplenEnhancebot golden fixture", () => {
  it(`fixture covers 14 items (source: ${fixture.sourceRepo}@${fixture.sourceCommit})`, () => {
    expect(fixture.items.length).toBe(14);
  });

  it("matches `expected` for every span within 1e-12 relative error", () => {
    let spanCount = 0;
    let maxRelError = 0;
    let maxRelErrorSpan = null;
    let bitMatches = 0;
    const overThreshold = [];

    for (const item of fixture.items) {
      const sfPrices = item.prices;
      for (const span of item.spans) {
        spanCount += 1;
        const ours = expectedStarforceCostExact({
          startStar: span.from,
          targetStar: span.to,
          sfPrices,
        });
        const expected = span.expected;
        const relError =
          expected === 0 ? Math.abs(ours - expected) : Math.abs(ours - expected) / Math.abs(expected);

        if (relError > maxRelError) {
          maxRelError = relError;
          maxRelErrorSpan = { itemId: item.itemId, from: span.from, to: span.to };
        }
        if (relError > RELATIVE_ERROR_LIMIT) {
          overThreshold.push({ itemId: item.itemId, from: span.from, to: span.to, relError });
        }
        if (Object.is(ours, expected)) bitMatches += 1;
      }
    }

    // Printed for the IMPL_PLAN_SH4.md §4 completion report (b)/(c)/(d) - not just asserted.
    // eslint-disable-next-line no-console
    console.log(`[SH-4] span total: ${spanCount}`);
    // eslint-disable-next-line no-console
    console.log(`[SH-4] max relative error: ${maxRelError} at ${JSON.stringify(maxRelErrorSpan)}`);
    // eslint-disable-next-line no-console
    console.log(`[SH-4] spans exceeding ${RELATIVE_ERROR_LIMIT}: ${overThreshold.length}`);
    // eslint-disable-next-line no-console
    console.log(
      `[SH-4] bit-identical spans: ${bitMatches}/${spanCount} (${((bitMatches / spanCount) * 100).toFixed(2)}%)`,
    );
    if (overThreshold.length) {
      // eslint-disable-next-line no-console
      console.log(`[SH-4] over-threshold spans (up to 20): ${JSON.stringify(overThreshold.slice(0, 20))}`);
    }

    expect(spanCount).toBeGreaterThanOrEqual(2000);
    expect(overThreshold).toEqual([]);
  });
});

describe("requiredPriceStars (design §9.1 missing-data gating depends on this)", () => {
  it("(19, 21) returns 10..20", () => {
    expect(requiredPriceStars(19, 21)).toEqual([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]);
  });

  it("(0, 22) returns 0..21", () => {
    expect(requiredPriceStars(0, 22)).toEqual(Array.from({ length: 22 }, (_, i) => i));
  });
});
