import { useMemo, useState } from "react";
import EventDialog from "./EventDialog.jsx";
import { buildEventViews } from "../domain/mergeTasks.js";
import { instantiateEventTemplate, removeUserEvent, upsertUserEvent } from "../domain/eventModel.js";
import { useEventStore } from "../storage/useEventStore.js";
import { formatUtcDeadline } from "../utils/format.js";
function uniqueId(){return `event:${globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`}`;}
export default function EventManagementSection({ templates, t }) {
  const store=useEventStore(); const [editing,setEditing]=useState(null); const [open,setOpen]=useState(false); const [error,setError]=useState("");
  const views=useMemo(()=>buildEventViews({events:store.state.items},new Date(),"ja"),[store.state.items]); const byId=new Map(views.map(view=>[view.id,view]));
  function save(input){const full={...input,id:input.id||uniqueId(),createdAt:input.createdAt||new Date().toISOString()};const candidate=upsertUserEvent(store.state,full);if(candidate.code==="invalidEvent")return{ok:false};const result=store.update(()=>candidate.state);if(result.ok){setOpen(false);setEditing(null);setError("");}return result;}
  function addTemplate(template){const copy=instantiateEventTemplate(template,uniqueId(),new Date());if(!copy){setError(t("event.templateInvalid"));return;}const candidate=upsertUserEvent(store.state,copy);if(candidate.code==="invalidEvent"){setError(t("event.templateInvalid"));return;}const result=store.update(()=>candidate.state);setError(result.ok?"":t("backup.saveFailed"));}
  return <section className="space-y-4 rounded-2xl border border-emerald-100 bg-white p-5 shadow-sm lg:col-span-2"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold tracking-[0.18em] text-emerald-600">EVENT</p><h2 className="mt-1 text-xl font-semibold text-slate-900">{t("event.manageTitle")}</h2><p className="mt-1 text-sm text-slate-500">{t("event.manageHint")}</p></div><button type="button" onClick={()=>{setEditing(null);setOpen(true);}} className="primary-button">＋ {t("event.add")}</button></div>{error?<div role="alert" className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">{error}</div>:null}<div className="rounded-xl border border-emerald-100 bg-emerald-50/40 p-3"><div className="flex flex-wrap items-center gap-2"><span className="mr-1 text-sm font-semibold text-slate-700">{t("event.templates")}</span>{(templates||[]).map(template=><button key={template.id} type="button" onClick={()=>addTemplate(template)} className="mini-button">＋ {template.label?.ja||template.id}</button>)}{!(templates||[]).length?<span className="text-sm text-slate-400">{t("event.noTemplates")}</span>:null}</div></div><div className="grid gap-3 md:grid-cols-2">{store.state.items.map(item=>{const view=byId.get(item.id);return <article key={item.id} className="rounded-xl border border-slate-200 bg-slate-50/60 p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><span className="text-xs font-bold text-emerald-600">{view?t(`event.${view.status}`):t("event.ended")}</span><h3 className="mt-1 truncate font-semibold text-slate-900">{item.title}</h3>{item.note?<p className="mt-1 truncate text-xs text-slate-500" title={item.note}>{item.note}</p>:null}</div><div className="flex gap-1"><button type="button" onClick={()=>{setEditing(item);setOpen(true);}} className="mini-button">{t("actions.edit")}</button><button type="button" onClick={()=>store.update(state=>removeUserEvent(state,item.id))} className="mini-button text-rose-600">{t("actions.delete")}</button></div></div><p className="mt-3 text-xs text-slate-500">{formatUtcDeadline(item.startsAt)} → {formatUtcDeadline(item.endsAt)}</p></article>;})}{!store.state.items.length?<div className="rounded-xl border border-dashed border-slate-300 py-10 text-center text-sm text-slate-500 md:col-span-2">{t("event.userEmpty")}</div>:null}</div><EventDialog open={open} item={editing} onClose={()=>{setOpen(false);setEditing(null);}} onSubmit={save} t={t}/></section>;
}
