import { useEffect, useRef, useState } from "react";

function localValue(value) { if (!value) return ""; const date=new Date(value); const shifted=new Date(date.getTime()-date.getTimezoneOffset()*60000); return shifted.toISOString().slice(0,16); }
function iso(value) { return value ? new Date(value).toISOString() : ""; }

export default function EventDialog({ open, item, onClose, onSubmit, t }) {
  const ref=useRef(null); const [title,setTitle]=useState(""); const [note,setNote]=useState(""); const [startsAt,setStartsAt]=useState(""); const [endsAt,setEndsAt]=useState(""); const [claimEndsAt,setClaimEndsAt]=useState(""); const [shopEndsAt,setShopEndsAt]=useState(""); const [showClaim,setShowClaim]=useState(false); const [showShop,setShowShop]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{ if(!open)return; setTitle(item?.title||""); setNote(item?.note||""); setStartsAt(localValue(item?.startsAt)); setEndsAt(localValue(item?.endsAt)); setClaimEndsAt(localValue(item?.claimEndsAt)); setShopEndsAt(localValue(item?.shopEndsAt)); setShowClaim(Boolean(item?.claimEndsAt)); setShowShop(Boolean(item?.shopEndsAt)); setError(""); },[item,open]);
  useEffect(()=>{const d=ref.current;if(open&&!d.open)d.showModal();if(!open&&d.open)d.close();},[open]);
  function submit(event){event.preventDefault(); if(!title.trim()||!startsAt||!endsAt){setError(t("event.formRequired"));return;} const result=onSubmit({...item,title:title.trim(),note:note.trim(),startsAt:iso(startsAt),endsAt:iso(endsAt),claimEndsAt:showClaim?iso(claimEndsAt):"",shopEndsAt:showShop?iso(shopEndsAt):""}); if(!result?.ok)setError(t("event.formInvalid"));}
  const field=(label,value,setValue,required=false)=><label className="block space-y-2 text-sm text-slate-700"><span>{label}{required?" *":""}</span><input type="datetime-local" required={required} className="field" value={value} onChange={e=>setValue(e.target.value)}/></label>;
  const optionalField=(label,value,setValue,onRemove)=><label className="block space-y-2 text-sm text-slate-700"><span className="flex items-center justify-between gap-2"><span>{label}</span><button type="button" onClick={onRemove} className="text-xs text-rose-600">{t("event.removeDeadline")}</button></span><input type="datetime-local" className="field" value={value} onChange={e=>setValue(e.target.value)}/></label>;
  return <dialog ref={ref} onClose={onClose} className="dialog-card backdrop:bg-slate-900/35"><form onSubmit={submit} className="space-y-5"><div className="flex items-center justify-between gap-4"><h2 className="text-xl font-semibold">{item?.id?t("event.edit"):t("event.add")}</h2><button type="button" onClick={onClose} className="mini-button">{t("actions.close")}</button></div><label className="block space-y-2 text-sm text-slate-700"><span>{t("event.name")} *</span><input autoFocus className="field" value={title} onChange={e=>setTitle(e.target.value)} placeholder={t("event.namePlaceholder")}/></label><label className="block space-y-2 text-sm text-slate-700"><span>{t("event.note")}</span><input className="field" maxLength={120} value={note} onChange={e=>setNote(e.target.value)} placeholder={t("event.notePlaceholder")}/></label><div className="grid gap-4 sm:grid-cols-2">{field(t("event.startsAt"),startsAt,setStartsAt,true)}{field(t("event.endsAt"),endsAt,setEndsAt,true)}{showClaim?optionalField(t("event.claimEndsAt"),claimEndsAt,setClaimEndsAt,()=>{setShowClaim(false);setClaimEndsAt("");}):null}{showShop?optionalField(t("event.shopEndsAt"),shopEndsAt,setShopEndsAt,()=>{setShowShop(false);setShopEndsAt("");}):null}</div>{!showClaim||!showShop?<details className="rounded-xl border border-dashed border-slate-300 bg-slate-50/70 p-3"><summary className="cursor-pointer text-sm font-medium text-slate-600">＋ {t("event.addExtraDeadline")}</summary><div className="mt-3 flex flex-wrap gap-2">{!showClaim?<button type="button" onClick={()=>setShowClaim(true)} className="mini-button">＋ {t("event.claimEndsAt")}</button>:null}{!showShop?<button type="button" onClick={()=>setShowShop(true)} className="mini-button">＋ {t("event.shopEndsAt")}</button>:null}</div></details>:null}{error?<p role="alert" className="text-sm text-rose-600">{error}</p>:null}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="secondary-button">{t("actions.cancel")}</button><button type="submit" className="primary-button">{t("actions.save")}</button></div></form></dialog>;
}
